name: 'Duplicate-Line Remover Action'
description: 'Removing the duplicate line in the given folder and uploads them to arifacts'
branding:
  icon: 'image'
  color: 'green'
inputs:
  input-folder:
    description: 'Folder in which input text are stored'
    required: true
    default: 'text'
  output-folder:
    description: 'Folder in which removed text are stored'
    required: true
    default: 'removed_text'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-folder }}
    - ${{ inputs.output-folder }}
